spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/appdb
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cdc-demo
      auto-offset-reset: earliest
      properties:
        max.poll.interval.ms: 300000
        session.timeout.ms: 45000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 8081
